# Generated by Django 5.0.3 on 2024-05-11 09:57

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.TextField(max_length=300, verbose_name='nickname')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[myapp.models.check_money], verbose_name='money')),
                ('date_registrate', models.DateField(validators=[myapp.models.check_date_created], verbose_name='date_registrate')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'client',
                'db_table': '"games_data"."client"',
                'ordering': ['nickname', 'date_registrate'],
            },
        ),
        migrations.CreateModel(
            name='GameClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'relationship games client',
                'verbose_name_plural': 'relationships games client',
                'db_table': '"games_data"."games_to_client"',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100, verbose_name='title')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[myapp.models.check_price], verbose_name='price')),
                ('clients', models.ManyToManyField(through='myapp.GameClient', to='myapp.client')),
            ],
            options={
                'verbose_name': 'games',
                'verbose_name_plural': 'games',
                'db_table': '"games_data"."games"',
                'ordering': ['title', 'genre', 'price'],
            },
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.games', verbose_name='game')),
            ],
            options={
                'verbose_name': 'relationship games genre',
                'verbose_name_plural': 'relationships games genre',
                'db_table': '"games_data"."games_to_genre"',
            },
        ),
        migrations.AddField(
            model_name='gameclient',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.games', verbose_name='games'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('date_public', models.DateField(default=django.utils.timezone.now, verbose_name='date_public')),
                ('estimation', models.DecimalField(decimal_places=1, default=0, max_digits=5, validators=[myapp.models.check_estimation], verbose_name='estimation')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.games')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
                'db_table': '"games_data"."comment"',
                'ordering': ['description', 'date_public', 'estimation'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='game',
            field=models.ManyToManyField(through='myapp.GameClient', to='myapp.games'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(choices=[('Fiction', 'Fiction'), ('PVP', 'PVP'), ('Horror', 'Horror')], max_length=200, verbose_name='title')),
                ('game', models.ManyToManyField(through='myapp.GameGenre', to='myapp.games')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genre',
                'db_table': '"games_data"."genre"',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='games',
            name='genres',
            field=models.ManyToManyField(through='myapp.GameGenre', to='myapp.genre'),
        ),
        migrations.AddField(
            model_name='gamegenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.genre', verbose_name='genre'),
        ),
        migrations.AlterUniqueTogether(
            name='gameclient',
            unique_together={('game', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='gamegenre',
            unique_together={('game', 'genre')},
        ),
    ]
