# Generated by Django 5.0.3 on 2024-06-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameclient',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameclient',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameclient',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.TextField(choices=[('Fiction', 'Fiction'), ('PVP', 'PVP'), ('Horror', 'Horror'), ('Card', 'Card'), ('Simulator', 'Sumilator'), ('Strategy', 'Strategy'), ('Casual', 'Casual')], max_length=200, verbose_name='title'),
        ),
    ]
