# Generated by Django 5.0.3 on 2024-06-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_gameclient_favorite_gameclient_in_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameclient',
            name='favorite',
        ),
    ]
