# Generated by Django 5.0.3 on 2024-06-08 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_gameclient_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.client', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='gameclient',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.games', verbose_name='games'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.TextField(choices=[('Fiction', 'Fiction'), ('PVP', 'PVP'), ('Horror', 'Horror'), ('Card', 'Card'), ('Simulator', 'Sumilator'), ('Strategy', 'Strategy'), ('Casual', 'Casual'), ('Adventures', 'Adventures'), ('Verbal', 'Verbal'), ('Puzzles', 'Puzzles')], max_length=200, verbose_name='title'),
        ),
    ]
