# Generated by Django 5.0.3 on 2024-06-08 15:01

import django.db.models.deletion
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_gameclient_client_alter_gameclient_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_registrate',
            field=models.DateField(auto_now_add=True, validators=[myapp.models.check_date_created], verbose_name='date_registrate'),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.games', verbose_name='game'),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.genre', verbose_name='genre'),
        ),
    ]
