# Generated by Django 5.0.3 on 2024-06-11 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_client_date_registrate_alter_gamegenre_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.client'),
        ),
    ]
