name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8 .
  container-job:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          PG_HOST: 127.0.0.1
          PG_PORT: 38734
          PG_USER: project
          PG_PASSWORD: project
        ports:
        - 38734:5432
    steps:
    - uses: actions/checkout@v2
    - name: Python installation
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Dependencies installation
      run: |
        python3 -m pip install --upgrade pip
        pip install -r req.txt
        chmod +x tests/test.sh
    - name: Test views
      run: ./tests/test.sh tests.test_views
    - name: Test models
      run: ./tests/test.sh tests.test_models
    - name: Test api
      run: ./tests/test.sh tests.test_api